version: '2'

networks:
  values_network:
    driver: bridge
    
volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:
    
services:
  mongodb:
    image: mongo
    container_name: device-configurations
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: eni
      MONGO_INITDB_ROOT_PASSWORD: softwaresystems1
    volumes:
      - ./db:/data/db

  schedulemanagementapi:
    build:
      context: .
      dockerfile: ScheduleManagementApi/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MONGO_CONNECTION_STRING: mongodb://eni:softwaresystems1@device-configurations:27017
    depends_on:
      - kafka
      - mongodb
    ports:
      - "5100:80"

  monitoringapp:
    build:
      context: .
      dockerfile: MonitoringApp/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SIGNALR_HUB_URL: http://localhost:5101/realtimehub
    depends_on:
      - kafka
    ports:
      - "5101:80"

  realtimedataconsumer:
    build:
      context: .
      dockerfile: RealTimeDataConsumer/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SIGNALR_HUB_URL: http://localhost:5101/realtimehub
    depends_on:
      - kafka
      - monitoringapp

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    networks:
      - values_network